map_type: costmap

obstacle_range: 4.0
raytrace_range: 4.0

transform_tolerance: 0.3

robot_radius: 0.0
inflation_radius: 0.7
xy_goal_tolerance: 0.1
yaw_goal_tolerance: 0.075
always_send_full_costmap: true

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

update_frequency: 5.0
publish_frequency: 2.0